openapi: 3.2.0
info:
  description: Copper API is based on the REST API interface provided for data exchange between a client and a server with the use of HTTPS requests and responses.
  title: Copper Platform Files API
  version: latest
servers:
- description: platform.copper.co
  url: https://api.copper.co/platform
- description: demo.copper.co
  url: https://api.stage.copper.co/platform
- description: testnet.copper.co
  url: https://api.testnet.copper.co/platform
tags:
- name: Files
paths:
  /files/{fileId}:
    get:
      parameters:
      - in: path
        name: fileId
        required: true
        schema:
          type: string
      summary: Download Files
      tags:
      - Files
      operationId: getFilesByFileId
      x-operation-id-source: derived
